// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var Caml_exceptions = require("rescript/lib/js/caml_exceptions.js");

var Err = /* @__PURE__ */Caml_exceptions.create("Binding.Err");

var StructureOrResource = {};

var getType = (x => {
      if (x instanceof Resource) { return "RESOURCE" }
      if (x instanceof Structure) { return "STRUCTURE" }
    });

function classify(v) {
  var match = getType(v);
  if (match === "RESOURCE") {
    return {
            TAG: /* Resource */0,
            _0: v
          };
  } else {
    return {
            TAG: /* Structure */1,
            _0: v
          };
  }
}

var Private = {
  getType: getType,
  classify: classify
};

function findClosestByPath(pos, array) {
  return Belt_Option.map(Caml_option.nullable_to_opt(pos.findClosestByPath(array)), classify);
}

exports.Err = Err;
exports.StructureOrResource = StructureOrResource;
exports.Private = Private;
exports.findClosestByPath = findClosestByPath;
/* No side effect */
