// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");

function samePosition(p1, p2) {
  if (Caml_obj.caml_equal(p1.x, p2.x)) {
    return Caml_obj.caml_equal(p2.y, p2.y);
  } else {
    return false;
  }
}

function testToPick(creep) {
  var freeCapacity = creep.store.getFreeCapacity(RESOURCE_ENERGY);
  return freeCapacity > 0;
}

function pickResource(creep, resource) {
  if (Caml_obj.caml_equal(creep.pickup(resource), ERR_NOT_IN_RANGE)) {
    creep.moveTo(resource.pos);
    return ;
  }
  
}

exports.samePosition = samePosition;
exports.testToPick = testToPick;
exports.pickResource = pickResource;
/* No side effect */
