// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");

function samePosition(p1, p2) {
  if (p1.x === p2.x && p2.y === p2.y) {
    return p1.roomName === p2.roomName;
  } else {
    return false;
  }
}

function pickResource(creep, resource) {
  if (Caml_obj.caml_equal(creep.pickup(resource), ERR_NOT_IN_RANGE)) {
    creep.moveTo(resource.pos);
    return ;
  }
  
}

exports.samePosition = samePosition;
exports.pickResource = pickResource;
/* No side effect */
