// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("rescript/lib/js/js_dict.js");
var RoleUpgrader = require("./RoleUpgrader.bs.js");
var RoleHarvester = require("./RoleHarvester.bs.js");

function loop(param) {
  Object.keys(Game.creeps).forEach(function (name) {
        var creep = Js_dict.get(Game.creeps, name);
        if (creep.memory.role === "harvester") {
          return RoleHarvester.roleHarvester(creep);
        } else {
          return RoleUpgrader.roleUpgrader(creep);
        }
      });
  
}

exports.loop = loop;
/* No side effect */
