// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Common = require("./Common.bs.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var RoleTransferer = require("./RoleTransferer.bs.js");

function transfererName(minePos) {
  return "Transferer" + minePos.roomName + String(minePos.x) + "." + String(minePos.y);
}

function roleTransferer(creep, minePos) {
  var freeCapacity = creep.store.getFreeCapacity(RESOURCE_ENERGY);
  if (creep.memory.transfering && creep.store.getUsedCapacity(RESOURCE_ENERGY) === 0) {
    creep.memory.transfering = false;
  }
  if (!creep.memory.transfering && freeCapacity === 0) {
    creep.memory.transfering = true;
  }
  if (creep.memory.transfering) {
    var match = creep.room.name;
    switch (match) {
      case "E32N28" :
          var allStructures = creep.room.find(107);
          var hasTask = RoleTransferer.findAndTransfer(creep, allStructures, [
                STRUCTURE_EXTENSION,
                STRUCTURE_SPAWN
              ]);
          if (!hasTask) {
            var hasTask$1 = RoleTransferer.findAndTransfer(creep, allStructures, [STRUCTURE_TOWER]);
            if (!hasTask$1) {
              var hasTask$2 = RoleTransferer.findAndTransfer(creep, allStructures, [STRUCTURE_CONTAINER]);
              if (!hasTask$2) {
                RoleTransferer.findAndTransfer(creep, allStructures, [STRUCTURE_STORAGE]);
              }
              
            }
            
          }
          break;
      case "E33N28" :
          creep.moveTo(0, 17);
          break;
      default:
        console.log("外矿搬运工跑到了其他房间");
    }
    return ;
  }
  var match$1 = creep.room.name;
  switch (match$1) {
    case "E32N28" :
        creep.moveTo(49, 17);
        break;
    case "E33N28" :
        var targetResource = Belt_Array.get(creep.room.find(106, {
                  filter: (function (resource) {
                      return Common.samePosition(resource.pos, minePos);
                    })
                }), 0);
        if (targetResource !== undefined) {
          Common.pickResource(creep, targetResource);
        } else {
          var resources = creep.room.find(106, {
                filter: (function (resource) {
                    return resource.amount > freeCapacity;
                  })
              });
          var resource = creep.pos.findClosestByPath(resources);
          if (!(resource == null)) {
            Common.pickResource(creep, resource);
          }
          
        }
        break;
    default:
      console.log("外矿搬运工跑到了其他房间");
  }
  
}

exports.transfererName = transfererName;
exports.roleTransferer = roleTransferer;
/* No side effect */
