// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Common = require("./Common.bs.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

function minerName(minePos) {
  return "OutpostMiner" + minePos.roomName + String(minePos.x) + "." + String(minePos.y);
}

function roleMiner(creep, minePos) {
  if (Common.samePosition(creep.pos, minePos)) {
    var sources = creep.room.find(105);
    var source = creep.pos.findClosestByPath(sources);
    return Belt_Option.forEach((source == null) ? undefined : Caml_option.some(source), (function (s) {
                  if (Caml_obj.caml_equal(creep.harvest(s), ERR_NOT_IN_RANGE)) {
                    creep.moveTo(s.pos);
                    return ;
                  }
                  
                }));
  }
  var match = creep.room.name;
  switch (match) {
    case "E32N28" :
        creep.moveTo(49, 17);
        break;
    case "E33N28" :
        creep.moveTo(minePos.x, minePos.y);
        break;
    default:
      console.log("外矿工人跑到了其他房间");
  }
  
}

exports.minerName = minerName;
exports.roleMiner = roleMiner;
/* No side effect */
