// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");
var Caml_array = require("rescript/lib/js/caml_array.js");

function roleUpgrader(creep) {
  if (creep.store.getUsedCapacity(RESOURCE_ENERGY) !== 0) {
    if (Caml_obj.caml_equal(creep.upgradeController(creep.room.controller), ERR_NOT_IN_RANGE)) {
      creep.moveTo(creep.room.controller.pos);
      return ;
    } else {
      return ;
    }
  }
  var sources = creep.room.find(105);
  if (Caml_obj.caml_equal(creep.harvest(Caml_array.get(sources, 0)), ERR_NOT_IN_RANGE)) {
    creep.moveTo(Caml_array.get(sources, 0).pos);
    return ;
  }
  
}

exports.roleUpgrader = roleUpgrader;
/* No side effect */
