// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

var controllerId = "5bbcaeba9099fc012e639797";

function roleClaimer(creep) {
  var match = creep.room.name;
  switch (match) {
    case "E31N28" :
        var controller = Game.getObjectById(controllerId);
        var controller$1 = (controller == null) ? undefined : Caml_option.some(controller);
        if (Caml_obj.caml_equal(creep.claimController(controller$1), ERR_NOT_IN_RANGE)) {
          creep.moveTo(controller$1.pos);
        }
        break;
    case "E32N28" :
        creep.moveTo(0, 29);
        break;
    default:
      console.log("claimer跑到了其他房间");
  }
  
}

exports.controllerId = controllerId;
exports.roleClaimer = roleClaimer;
/* No side effect */
