// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Common = require("./Common.bs.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

function minerName(minePos) {
  return "Miner" + String(minePos.x) + "." + String(minePos.y);
}

function roleMiner(creep, minePos) {
  if (Common.samePosition(creep.pos, minePos)) {
    console.log("miner working", creep.name);
    var sources = creep.room.find(105);
    var source = creep.pos.findClosestByPath(sources);
    var source$1 = (source == null) ? undefined : Caml_option.some(source);
    console.log(sources, source$1);
    return Belt_Option.forEach(source$1, (function (s) {
                  if (Caml_obj.caml_equal(creep.harvest(s), ERR_NOT_IN_RANGE)) {
                    creep.moveTo(s.pos);
                    return ;
                  }
                  
                }));
  }
  var moveErr = creep.moveTo(minePos.x, minePos.y);
  console.log("miner moving", creep.name, moveErr);
  
}

exports.minerName = minerName;
exports.roleMiner = roleMiner;
/* No side effect */
