// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("rescript/lib/js/js_dict.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");
var Caml_array = require("rescript/lib/js/caml_array.js");

function roleHarvester(creep) {
  if (creep.store.getFreeCapacity() > 0) {
    var sources = creep.room.find(105);
    if (Caml_obj.caml_equal(creep.harvest(Caml_array.get(sources, 0)), ERR_NOT_IN_RANGE)) {
      creep.moveTo(Caml_array.get(sources, 0).pos);
      return ;
    } else {
      return ;
    }
  }
  var spawn1 = Js_dict.get(Game.spawns, "Spawn1");
  if (Caml_obj.caml_equal(creep.transfer(spawn1, RESOURCE_ENERGY), ERR_NOT_IN_RANGE)) {
    creep.moveTo(spawn1.pos);
    return ;
  }
  
}

exports.roleHarvester = roleHarvester;
/* No side effect */
