// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_SetString = require("rescript/lib/js/belt_SetString.js");

var init = {
  hasTaskCreeps: undefined
};

function addTask(tasks, creep) {
  return {
          hasTaskCreeps: Belt_SetString.add(tasks.hasTaskCreeps, creep.name)
        };
}

function hasTask(tasks, creep) {
  return Belt_SetString.has(tasks.hasTaskCreeps, creep.name);
}

function merge(tasks1, tasks2) {
  return {
          hasTaskCreeps: Belt_SetString.union(tasks1.hasTaskCreeps, tasks2.hasTaskCreeps)
        };
}

exports.init = init;
exports.addTask = addTask;
exports.hasTask = hasTask;
exports.merge = merge;
/* No side effect */
